services:
  searxng:
    build:
      context: .
      dockerfile: searxng.dockerfile
    container_name: perplexify-searxng-1
    environment:
      - SEARXNG_BOTDETECTION_ENABLED=false
    ports:
      - 4000:8080
    networks:
      - perplexify-network
    restart: unless-stopped

  app:
    # Build from local Dockerfile and code
    build:
      context: .
      dockerfile: app.dockerfile
    container_name: perplexify-app-1
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATA_DIR=/home/perplexify
      - NODE_ENV=${NODE_ENV:-development}
    ports:
      - 3000:3000
    networks:
      - perplexify-network
    volumes:
      - backend-dbstore:/home/perplexify/data
      - uploads:/home/perplexify/uploads
    restart: unless-stopped

networks:
  perplexify-network:

volumes:
  backend-dbstore:
  uploads: