services:
  searxng:
    build:
      context: .
      dockerfile: searxng.dockerfile
    container_name: perplexify-searxng-dev
    environment:
      - SEARXNG_BOTDETECTION_ENABLED=false
    ports:
      - 4000:8080
    networks:
      - perplexify-network
    restart: unless-stopped

networks:
  perplexify-network: 