services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - perplexica-network
    restart: unless-stopped

  app:
    # Build from local Dockerfile and code for development
    build:
      context: .
      dockerfile: app.dockerfile
    environment:
      - SEARXNG_API_URL=http://searxng:8080
      - DATA_DIR=/home/perplexica
    ports:
      - 3000:3000
    networks:
      - perplexica-network
    volumes:
      - backend-dbstore:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
      - ./drizzle:/home/perplexica/drizzle
      - ./entrypoint.sh:/home/perplexica/entrypoint.sh
      - ./package.json:/home/perplexica/package.json
      - ./yarn.lock:/home/perplexica/yarn.lock
      - ./tsconfig.json:/home/perplexica/tsconfig.json
      - ./next.config.mjs:/home/perplexica/next.config.mjs
      - ./next-env.d.ts:/home/perplexica/next-env.d.ts
      - ./postcss.config.js:/home/perplexica/postcss.config.js
      - ./drizzle.config.ts:/home/perplexica/drizzle.config.ts
      - ./tailwind.config.ts:/home/perplexica/tailwind.config.ts
    restart: unless-stopped

networks:
  perplexica-network:

volumes:
  backend-dbstore:
  uploads: