import SearchOrchestrator from './orchestrator';
import prompts from '../prompts';

export const orchestratorHandlers: Record<string, SearchOrchestrator> = {
  webSearch: new SearchOrchestrator({
    activeEngines: [],
    queryGeneratorPrompt: prompts.webSearchRetrieverPrompt,
    responsePrompt: prompts.webSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: true,
    planningPrompt: prompts.webSearchPlanningPrompt,
  }),
  academicSearch: new SearchOrchestrator({
    activeEngines: ['arxiv', 'google scholar', 'pubmed'],
    queryGeneratorPrompt: prompts.academicSearchRetrieverPrompt,
    responsePrompt: prompts.academicSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: true,
    summarizer: false,
    planningPrompt: prompts.academicSearchPlanningPrompt,
  }),
  writingAssistant: new SearchOrchestrator({
    activeEngines: [],
    queryGeneratorPrompt: '',
    responsePrompt: prompts.writingAssistantPrompt,
    rerank: true,
    rerankThreshold: 0,
    searchWeb: false,
    summarizer: false,
    planningPrompt: prompts.writingAssistantPlanningPrompt,
  }),
  wolframAlphaSearch: new SearchOrchestrator({
    activeEngines: ['wolframalpha'],
    queryGeneratorPrompt: prompts.wolframAlphaSearchRetrieverPrompt,
    responsePrompt: prompts.wolframAlphaSearchResponsePrompt,
    rerank: false,
    rerankThreshold: 0,
    searchWeb: true,
    summarizer: false,
    planningPrompt: prompts.wolframAlphaSearchPlanningPrompt,
  }),
  youtubeSearch: new SearchOrchestrator({
    activeEngines: ['youtube'],
    queryGeneratorPrompt: prompts.youtubeSearchRetrieverPrompt,
    responsePrompt: prompts.youtubeSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
    planningPrompt: prompts.youtubeSearchPlanningPrompt,
  }),
  redditSearch: new SearchOrchestrator({
    activeEngines: ['reddit'],
    queryGeneratorPrompt: prompts.redditSearchRetrieverPrompt,
    responsePrompt: prompts.redditSearchResponsePrompt,
    rerank: true,
    rerankThreshold: 0.3,
    searchWeb: true,
    summarizer: false,
    planningPrompt: prompts.redditSearchPlanningPrompt,
  }),
}; 